name: "Build Package"
on: ["push", "workflow_dispatch"]

jobs:
  build:
    name: "Build Munki Package"
    runs-on: "macos-11"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Build Package"
        run: "code/tools/make_munki_mpkg.sh"
